name: Python Async API

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide
        pip install flake8-html
        pip install -r requirements.txt

    - name: Lint with wemake-python-styleguide
      run: |
        flake8 --format=html --htmldir=flake-report src/
